name = "Jughead"
license = "MIT"
licenselink = "https://github.com/ananthb/jughead/blob/main/LICENSE"
description = "Jughead is a portfolio and blog theme for Hugo. The philosophy of Jughead is to keep things simple, useful, and fast. Jughead is responsive and loads quickly on all devices."
homepage = "https://github.com/ananthb/jughead"
demosite = "https://ananthb.github.io/jughead/"
tags = [
  "portfolio",
  "blog",
  "simple",
  "responsive",
  "minimal",
  "personal",
  "clean",
  "shortcodes",
]
features = ["resume", "blog", "responsive", "comments", "Syntax highlighting"]
min_version = "0.120.0"

[author]
name = "Ananth Bhaskararaman"
homepage = "https://github.com/ananthb"

[original]
name = "Archie"
homepage = "https://athul.github.io/archie"
repo = "https://github.com/athul/archie"
