baseURL = "https://example.com"
languageCode = "en-in"
title = "Jughead"
copyright = "© Ananth Bhaskararaman"

# Code highlighting
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Site parameters
[params]
attribution = true    # show theme attribution in the footer
mode = "auto"         # color-mode → light,dark,toggle or auto
useCDN = false        # don't use CDNs for fonts and icons, instead serve them locally.
subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/ananthb/jughead)"
mathjax = true        # enable MathJax support
katex = true          # enable KaTeX support

# Comments powered by utterances & GitHub issues.
# Follow the setup instructions at https://utteranc.es.
[[params.utterances]]
repo = "ananthb/jughead"
# issueTerm = "pathname"
# theme = "github-light"

# Social Tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ananthb/jughead"
[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/me/"
[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/ananth/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
