baseURL = "https://example.com"
languageCode = "en-in"
title = "Jughead"
copyright = "© Ananth Bhaskararaman"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
attribution = true
mode = "auto"
useCDN = false
subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/ananthb/jughead)"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ananthb/jughead"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/me/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/ananth/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
